[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "pyRATS"
version = "0.0.1"
description = "Riemannian Alignment of Tangent Spaces (RATS) for dimensionality reduction"
readme = "README.md"
license-files = ["License"]
requires-python = ">=3.9"

dependencies = [
    "numpy",
    "scikit-learn",
    "scipy",
    "joblib",
    "multiprocess",
    "tqdm",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pandas",
    "Pillow",
    "matplotlib",
    "imageio",
    "seaborn",
]

examples = [
    "pandas",
    "matplotlib",
    "imageio",
    "seaborn",
]